destino.usuario=http://usuario-ms:8081
destino.restaurante=http://restaurante-ms:8082
destino.menu=http://menu-ms:8083
destino.reserva=http://reserva-ms:8084
destino.calificacion=http://calificacion-ms:8085