# Puerto del Gateway
server.port=8080

# Destinos locales (perfil default)
destino.usuario=http://localhost:8081
destino.restaurante=http://localhost:8082
destino.menu=http://localhost:8083
destino.reserva=http://localhost:8084
destino.calificacion=http://localhost:8085
destino.orden=http://localhost:8086
destino.delivery=http://localhost:8087
destino.pago=http://localhost:8088
destino.promocion=http://localhost:8089
destino.reporte=http://localhost:8090
